### PR TITLE
Pseudo command

### PR DESCRIPTION
**Pull request by conorpp**
Basically replaces having to do this

```
[[commands]]
cmd = "Erase"
start = 0x0
end = 0xC00 

[[commands]]
cmd = "Load"
file = "example-binaries/blinky-red-signed.bin"
src = 512
dst = 512

[[commands]]
cmd = "Load"
file = "example-binaries/blinky-red-signed.bin"
len = 512
```

With:

```
[[pseudo-commands]]
cmd = "UploadSignedImage"
```

### CODE REVIEW

**Comment by nickray** [comment]
I like the idea, would prefer calling this a ` BootCommandSequenceDescriptor`, but placing under regular `[[commands]]` with `seq =` in place of `cmd =`. This way I think the naming is more precise, and can determine order of operations. And maybe have some enum-style modeling.

Will push commits on top after playing a bit.

**Comment by conorpp** [comment]
@nickray ready to merge if you're okay with it.

**Comment by nickray** [comment]
The thing is that StartEnabled bricked my prototype, I need to understand why that happened.

**Comment by nickray** [comment]
It turns out that `StartEnabled` is actually an illegal state (UM11126 rev2.1, 51.7.1.4, Table 1064):

image

Completely reworked this, and added support to leave debug access settings untouched (if not specified).

**Pull request merged**
